name 'dhoppe-rsnapshot'
version '0.0.10'

author 'Dennis Hoppe'
license 'GPLv2'
project_page 'http://github.com/dhoppe/puppet-rsnapshot'
source 'git://github.com/dhoppe/puppet-rsnapshot'
summary 'Rsnapshot Module'
description 'Rsnapshot Module for Debian, Ubuntu'
dependency 'dhoppe/puppet', '>=0.0.1'
